### ISSUE TITLE
encoding error in transaction

### ISSUE THREAD

**Issue by hermanius** [nakagami/firebirdex#12]
Hi,

it looks like there is an encoding problem when using transactions.
For example when I try to do this inside a function:
```
    Firebirdex.transaction(Cvodvd.WisaDB.conn(), fn conn ->
      Firebirdex.query(conn, "DELETE FROM CVODVD_ODB")
      Enum.each(records,fn record ->
        Firebirdex.query(conn, sql, [
          record["voo_code"],
          record["vo_code"],
          record["odb_code"],
          record["vov"],
          record["vok"],
          record["oc"]
        ])
      end)
```

I get the following stack trace:

[error] GenServer #PID<0.538.0> terminating
** (DBConnection.ConnectionError) client #PID<0.657.0> stopped: ** (FunctionClauseError) no function clause matching in Firebirdex.Encoding.from_string!/2
    (firebirdex 0.3.3) lib/firebirdex/encoding.ex:2: Firebirdex.Encoding.from_string!("DELETE FROM CVODVD_ODB", nil)
    (firebirdex 0.3.3) lib/firebirdex/connection.ex:62: Firebirdex.Connection.handle_prepare/3
    (db_connection 2.4.2) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.4.2) lib/db_connection.ex:1349: DBConnection.prepare/4
    (db_connection 2.4.2) lib/db_connection.ex:1342: DBConnection.run_prepare/4
    (db_connection 2.4.2) lib/db_connection.ex:1354: DBConnection.run_prepare_execute/5
    (db_connection 2.4.2) lib/db_connection.ex:595: DBConnection.parsed_prepare_execute/5
    (db_connection 2.4.2) lib/db_connection.ex:587: DBConnection.prepare_execute/4
    (firebirdex 0.3.3) lib/firebirdex.ex:23: Firebirdex.query/4
    (cvodvd 0.1.0) lib/cvodvd/sync/odb_codes.ex:49: anonymous fn/2 in Cvodvd.Sync.OdbCodes.update_wisa/1
    (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4
    (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6
    (elixir 1.13.3) src/elixir.erl:296: :elixir.recur_eval/3
    (elixir 1.13.3) src/elixir.erl:274: :elixir.eval_forms/3
    (iex 1.13.3) lib/iex/evaluator.ex:310: IEx.Evaluator.handle_eval/3
    (iex 1.13.3) lib/iex/evaluator.ex:285: IEx.Evaluator.do_eval/3
    (iex 1.13.3) lib/iex/evaluator.ex:274: IEx.Evaluator.eval/3
    (iex 1.13.3) lib/iex/evaluator.ex:169: IEx.Evaluator.loop/1
    (iex 1.13.3) lib/iex/evaluator.ex:32: IEx.Evaluator.init/4
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

    (db_connection 2.4.2) lib/db_connection/connection.ex:198: DBConnection.Connection.handle_cast/2
    (connection 1.1.0) lib/connection.ex:810: Connection.handle_async/3
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.17) proc_lib.erl:236: :proc_lib.wake_up/3
Last message: {:"$gen_cast", {:stop, #Reference<0.50204116.1522925569.38858>, %DBConnection.ConnectionError{message: "client #PID<0.657.0> stopped: ** (FunctionClauseError) no function clause matching in Firebirdex.Encoding.from_string!/2\n    (firebirdex 0.3.3) lib/firebirdex/encoding.ex:2: Firebirdex.Encoding.from_string!(\"DELETE FROM CVODVD_ODB\", nil)\n    (firebirdex 0.3.3) lib/firebirdex/connection.ex:62: Firebirdex.Connection.handle_prepare/3\n    (db_connection 2.4.2) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4\n    (db_connection 2.4.2) lib/db_connection.ex:1349: DBConnection.prepare/4\n    (db_connection 2.4.2) lib/db_connection.ex:1342: DBConnection.run_prepare/4\n    (db_connection 2.4.2) lib/db_connection.ex:1354: DBConnection.run_prepare_execute/5\n    (db_connection 2.4.2) lib/db_connection.ex:595: DBConnection.parsed_prepare_execute/5\n    (db_connection 2.4.2) lib/db_connection.ex:587: DBConnection.prepare_execute/4\n    (firebirdex 0.3.3) lib/firebirdex.ex:23: Firebirdex.query/4\n    (cvodvd 0.1.0) lib/cvodvd/sync/odb_codes.ex:49: anonymous fn/2 in Cvodvd.Sync.OdbCodes.update_wisa/1\n    (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4\n    (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6\n    (elixir 1.13.3) src/elixir.erl:296: :elixir.recur_eval/3\n    (elixir 1.13.3) src/elixir.erl:274: :elixir.eval_forms/3\n    (iex 1.13.3) lib/iex/evaluator.ex:310: IEx.Evaluator.handle_eval/3\n    (iex 1.13.3) lib/iex/evaluator.ex:285: IEx.Evaluator.do_eval/3\n    (iex 1.13.3) lib/iex/evaluator.ex:274: IEx.Evaluator.eval/3\n    (iex 1.13.3) lib/iex/evaluator.ex:169: IEx.Evaluator.loop/1\n    (iex 1.13.3) lib/iex/evaluator.ex:32: IEx.Evaluator.init/4\n    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\n", reason: :error, severity: :error}, %Firebirdex.Connection{charset: nil, conn: {:conn, #Port<0.19>, '<USER>', '<PASSWORD>', :cp1252, true, 249183553855695752259025901539470500830, 103567129941906026288434133422668171601172440229759169995026977034920371872160430608384320594353571829468899157299956474780500090406357796085895868999995244459472424811556563038572862879791243349977983990579044355312857790295210876632078415198225837565311458142442744960410283559510011215171673400394910688133, :undefined, 'Srp256', true, :undefined, :undefined, 0, 118, 12, 'Europe/Brussels', %{}, %{}}}}}
State: {Firebirdex.Connection, %Firebirdex.Connection{charset: nil, conn: {:conn, #Port<0.19>, '<USER>', '<PASWORD>', :cp1252, true, 249183553855695752259025901539470500830, 103567129941906026288434133422668171601172440229759169995026977034920371872160430608384320594353571829468899157299956474780500090406357796085895868999995244459472424811556563038572862879791243349977983990579044355312857790295210876632078415198225837565311458142442744960410283559510011215171673400394910688133, :undefined, 'Srp256', true, :undefined, :undefined, 0, 118, 12, 'Europe/Brussels', %{}, %{}}}}
** (FunctionClauseError) no function clause matching in Firebirdex.Encoding.from_string!/2    
    
    The following arguments were given to Firebirdex.Encoding.from_string!/2:
    
        # 1
        "DELETE FROM CVODVD_ODB"
    
        # 2
        nil
    
    Attempted function clauses (showing 10 out of 39):
    
        def from_string!(s, :utf_8)
        def from_string!(s, :cp932)
        def from_string!(s, :cp737)
        def from_string!(s, :cp437)
        def from_string!(s, :cp850)
        def from_string!(s, :cp865)
        def from_string!(s, :cp860)
        def from_string!(s, :cp863)
        def from_string!(s, :cp775)
        def from_string!(s, :cp862)
        ...
        (29 clauses not shown)
    
    (firebirdex 0.3.3) lib/firebirdex/encoding.ex:2: Firebirdex.Encoding.from_string!/2
    (firebirdex 0.3.3) lib/firebirdex/connection.ex:62: Firebirdex.Connection.handle_prepare/3
    (db_connection 2.4.2) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.4.2) lib/db_connection.ex:1349: DBConnection.prepare/4
    (db_connection 2.4.2) lib/db_connection.ex:1342: DBConnection.run_prepare/4
    (db_connection 2.4.2) lib/db_connection.ex:1354: DBConnection.run_prepare_execute/5
    (db_connection 2.4.2) lib/db_connection.ex:595: DBConnection.parsed_prepare_execute/5
    (db_connection 2.4.2) lib/db_connection.ex:587: DBConnection.prepare_execute/4
    (firebirdex 0.3.3) lib/firebirdex.ex:23: Firebirdex.query/4
    (cvodvd 0.1.0) lib/cvodvd/sync/odb_codes.ex:49: anonymous fn/2 in Cvodvd.Sync.OdbCodes.update_wisa/1
    (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4

**Comment by nakagami** [comment]
I was able to write a test that produces the same error.
I'll fix it later.

**Comment by nakagami** [comment]
I need you to check to see if it is fixed in issue12 branch.

**Comment by hermanius** [comment]
Yes, the issue12 branch solves the issue. Thank you, once again.

**Comment by nakagami** [comment]
version 0.3.4 releaesed
