### ISSUE TITLE
DBConnection.close misinterpretation?

### ISSUE THREAD

**Issue by hermanius** [nakagami/firebirdex#3]
Hi,

while using Firebirdex and monitoring the Firebirdsql database I noticed a cumulation of prepared statements in the database server, ultimately leading to a crash.
Apparently prepared queries are cashed by the database server on a connection, and must explicitly be closed to be cleaned up.
This issues does not present itself when you just open the database connection, do a query, and close the connection. It does present itself however when you open a connection, and do lots of queries (Firebirdex.query) on that same connection.

In the DBConnection specification there is a close function, with a handle_close callback which should do this cleanup of a prepared statement, but I noticed in your implementation of the Firebirdex.Connection.handle_close function you are closing the connection (:efirebirdsql_protocol.close), which is basically the same as Firebirdex.Connection.disconnect.

Is it possible you misinterpreted the close/handle_close as being a disconnect, while it actually should be a cleanup of a prepared query?

I don't know enough of the underlying :efirebirdsql_protocol, to know which function to call to do the prepared query cleanup to create a pull request.
Can you help?

**Comment by nakagami** [comment]
I see, I have to free_statement in DBConnection.close().
In the current implementation, Firebirdex.Connection does not hold a Firebirdex.Query.
So I can't immediately modify it to drop all statement handles on close().
I will try to do it, but it will be a bit of a big modification, so please wait.

**Comment by nakagami** [comment]
No, wait a minute.

I think Firebird Server is deleting the prepared statement internally when it closes the connection.

Maybe it's not cleanup on close, but that the prepared statement is too cached before DBConnection.close()?

Could you please provide a simple program?
I need an example of Firebird Server crashing because the prepared statement is not closed by DBConnection.close().

**Comment by nakagami** [comment]
Does this fix not solve the problem?
https://github.com/nakagami/firebirdex/commit/bf0c580f39f0e38faeff3d58ce90d7177ebb4181

**Comment by hermanius** [comment]
When the connection is closed the prepared statements are indeed deleted by the server. However I think according to the DBConnection.handle_close specification the intention is to only do a free_statement and not a connection close.
https://hexdocs.pm/db_connection/DBConnection.html#c:handle_close/3

Fix bf0c580 solves the problem for the pings, but not for Firebirdex.query. So it partially solves the problem in that pings don't add to the number of cashed prepared statements, but the Firebird.query function does.
I did some more investigation into the library, and it turns out you are returning the prepared statement inside the Query structure as Query.stmt, which is great because it probably could be used to call DBConnection.close(), which then should be updated to do a free_statement in stead of closing the connection.
Would you like me to try to create a PR for that?

I also noticed in our database monitor that ping & Firebirdex.query are increasing the number of pending transactions, also leading up to a crash when going over a certain limit.
I have to investigate it, but I think the FirebirdSQL database can be configured to automatically open a new transaction on every query, while not automatically closing the transaction. And I seem to remember there is a connection parameter that prevents that, or one would have to execute every query inside a transaction (DBConnection.transaction).
Should we handle this also in this issue, or would you like me to open a new issue for this?

**Comment by nakagami** [comment]
I see, upon closer review of the documentation https://hexdocs.pm/db_connection/DBConnection.html#c:handle_close/3,
 that handle_close() handles the dropping of prepared statements (from Firbird's point of view).

**Comment by hermanius** [comment]
Yes, I suppose it is the call-back handler for DBConnection.close
https://hexdocs.pm/db_connection/DBConnection.html#close/3

**Comment by nakagami** [comment]
@hermanius Thanks.
I think PR #5 solved the problem.

Do you think this Issue can be closed?

**Comment by hermanius** [comment]
I think indeed it solved the issue #3 of the prepared statements not being freed, but there is also the issue of pending transactions. Should we take that into a separate issue?

**Comment by nakagami** [comment]
Please create a separate issue for transaction issues.
Thanks
