### ISSUE TITLE
Prepared statements cache

### ISSUE THREAD

**Issue by hermanius** [nakagami/firebirdex#9]
Hi,

This is not really an issue, but more of an idea I would like to discuss with you.
The whole thing with the prepared statements made me thinking. The way Firebirdex is handling it right now is OK in the sense that there is no build-up of prepared statements on the server anymore. Prepared statements however are interesting because of their performance enhancements.
Therefore I'm thinking about creating a cache of prepared statements on the client, maybe by storing them in an ETS table with the hash of the statement as the key. Possible improvements could be to store a certain maximum of statements, and deleting statements that have not been used when the maximum is reached.
This could be done by some options on the connection (keep_prepared_statements?, max_prepared_statements, ...), and/or options on the Firebird.query function itself.
Is this something you see as valuable to Firebirdex, then I will try to build it into Firebirdex. If it's something that you don't like to have in Firebirdex, I can still develop it as a front-end to Firebirdex for myself.

What do you think?

**Comment by nakagami** [comment]
I am opposed to caching prepaid statements at the client for the following reasons

- It would be complicated
- It uses a lot of memory
- Can't handle statement processing leaks well?

Since db_connection's handle_decrate() and handle_deallocate() handle the equivalent of Firebird's statement handles, wouldn't it be better for functions that use db_connection to cache them?

**Comment by hermanius** [comment]
- _It would be complicated_: Maybe I'm overlooking some of the complexity, but hashing the statements and using the hash as a key in an ETS table does not seem to be so complicated at first sight. Where exactly do you see the complexity? (Of course I'm willing to help out)
- _It uses a lot of memory_ : I will have to figure out how much memory is used to cache a statement, but memory use could be limited by max_prepared_statements and cleanup of oldest or least used statements when the maximum is reached.
And of course there is still the option of completely opting out of prepared statement caching with a keep_prepared_statements? connection option, defaulting to false, or setting max_prepared_statements to 0.
- _Can't handle statement processing leaks well?_ : I don't really understand this one.

_Since db_connection's handle_decrate() and handle_deallocate() handle the equivalent of Firebird's statement handles, wouldn't it be better for functions that use db_connection to cache them?_
Isn't it Firebirdex that is using the DBConnection functions, and therefore indeed a good candidate to do the caching?

I'm just launching an idea. I'm perfectly fine if you don't like the idea, and want to close the issue. I can still do a prepared statement cache outside of Firebirdex. No hard feelings at all, and very grateful that you have created this great library.
